version=0.1
[default.package.parameters]
s3_bucket = "lambda-function-3210"
region = "us-east-1"
image_repository="624448302051.dkr.ecr.us-east-1.amazonaws.com/python-container-example"
[default.deploy.parameters]
s3_bucket = "lambda-function-3210"
region = "us-east-1"
image_repository="624448302051.dkr.ecr.us-east-1.amazonaws.com/python-container-example"