Resources:
  MyUser:
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
      Policies:
        - PolicyName: Cool-Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
                - Sid: IamListAccess
                  Effect: Allow
                  Action:
                  - 'iam:ListRoles'
                  - 'iam:ListUsers'
                  Resource: '*'
  MyInclinePolicy:
    Type: 'AWS::IAM::UserPolicy'
    Properties:
      PolicyName: MyInclinePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 'ec2:*'
            Resource: '*'
      UserName: !Ref MyUser
